### ISSUE TITLE
The generated link is broken.

### ISSUE THREAD

**Issue by Shrekie** [bukinoshita/share-facebook#1]
The generated link does not refer to the url among other things. 
Please take a look, this is top result for "facebook share npm"

**Comment by bukinoshita** [comment]
It's working as expected.

![share-facebook](https://user-images.githubusercontent.com/6929565/38230044-5f0bce50-36e2-11e8-9946-e3a889222792.gif)

**Comment by Shrekie** [comment]
```
const shareFacebook = require('share-facebook')

shareFacebook({
  quote: 'Check this library to help you create share facebook url',
  url: 'https://bukinoshita.io',
  redirect_uri: 'https://bukinoshita.io',
  app_id: '145634995501895'
})
```

`https://www.facebook.com/dialog/share?app_id=145634995501895&redirect_uri=https://bukinoshita.io&display=page&quote=Check%20this%20library%20to%20help%20you%20create%20share%20facebook%20url`

This is my result.

**Comment by bukinoshita** [comment]
> Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

This usually happens if you have entered the wrong details when you created the App in Facebook. Or have you changed a URL's of an existing App?

Can you please recheck the settings of your APP in this page?

https://developers.facebook.com/apps

- Select the correct App and click in the edit button;
- Check the URLs & paths are correctly entered and are pointing to the site where you have installed Facebook plugin.

**Comment by Shrekie** [comment]
https://developers.facebook.com/docs/

145634995501895

Are compatible, it is the ones you use in your example.
Of course the 'The domain of this URL isn't included in the app's domains' would show up. Because your module doesn't add a url in the link.

**Comment by bukinoshita** [comment]
You are using `url` param in your example, but [you actually need to pass a `href`](https://github.com/bukinoshita/share-facebook#href). Your `redirect_uri` is also different.

Try using:

```
shareFacebook({
  quote: 'Sharing with FB',
  href: 'https://developers.facebook.com/docs/',
  redirect_uri: 'https://developers.facebook.com/tools/explorer',
  app_id: '145634995501895',
  display: 'page'
})
```

I'm also using this module in `production` here if you need another example ([example](https://github.com/bukinoshita/hackdisrupt/blob/staging/components/share-facebook.js#L10-L14))

**Comment by Shrekie** [comment]
Changing to href seems to work great.

NPM page has url as parameter in its usage example.
https://www.npmjs.com/package/share-facebook
